"""initial

Revision ID: 263d21436bf7
Revises: c75bb05a3367
Create Date: 2026-07-23 16:31:13.439760

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '263d21436bf7'
down_revision: str | Sequence[str] | None = 'c75bb05a3367'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_bindings', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('rule_bindings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('rule_bindings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_bindings', 'updated_at')
    op.drop_column('rule_bindings', 'created_at')
    op.drop_column('rule_bindings', 'priority')
    # ### end Alembic commands ###
