apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aimp.fullname" . }}-config
  labels:
    {{- include "aimp.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  QUEUE_REDIS_URL: {{ .Values.config.QUEUE_REDIS_URL | quote }}
  DATABASE_URL: {{ .Values.config.DATABASE_URL | quote }}
  MODEL_STORE_PATH: {{ .Values.config.MODEL_STORE_PATH | quote }}
  CACHE_TTL: {{ .Values.config.CACHE_TTL | quote }}
  MAX_FRAME_SIZE: {{ .Values.config.MAX_FRAME_SIZE | quote }}
