apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aimp.fullname" . }}-secret
  labels:
    {{- include "aimp.labels" . | nindent 4 }}
type: Opaque
data:
  jwt_secret_key: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  {{- if .Values.mysql.enabled }}
  mysql_root_password: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
  mysql_password: {{ .Values.secrets.mysqlPassword | b64enc | quote }}
  {{- end }}
